/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--color-background)",
        "on-background": "var(--color-on-background)",
        surface: "var(--color-surface)",
        "on-surface": "var(--color-on-surface)",
        "outline-variant": "var(--color-outline-variant)",
        secondary: "var(--color-secondary)",
        "surface-variant": "var(--color-surface-variant)",
        
        "surface-container": "#ebeef0",
        "on-primary": "#ffffff",
        "secondary-container": "#dde2f3",
        "on-primary-fixed": "#00210c",
        "error": "#ba1a1a",
        "surface-bright": "#f7fafc",
        "on-secondary-fixed-variant": "#414754",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#4ae183",
        "on-surface-variant": "#3d4a3e",
        "surface-container-highest": "#e0e3e5",
        "tertiary-fixed": "#ffdbd0",
        "on-tertiary": "#ffffff",
        "primary": "#006d37",
        "inverse-surface": "#2d3133",
        "on-secondary-container": "#5e6473",
        "on-tertiary-fixed": "#390c00",
        "on-tertiary-container": "#772e14",
        "outline": "#6c7b6d",
        "tertiary-fixed-dim": "#ffb59d",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#161c27",
        "surface-container-high": "#e5e9eb",
        "secondary-fixed-dim": "#c1c6d7",
        "primary-container": "#2ecc71",
        "tertiary-container": "#ff9875",
        "on-tertiary-fixed-variant": "#793015",
        "surface-tint": "#006d37",
        "inverse-on-surface": "#eef1f3",
        "surface-container-low": "#f1f4f6",
        "tertiary": "#98472a",
        "surface-dim": "#d7dadc",
        "inverse-primary": "#4ae183",
        "secondary-fixed": "#dde2f3",
        "primary-fixed": "#6bfe9c",
        "on-primary-fixed-variant": "#005228",
        "on-primary-container": "#005027"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "1rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "4px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "margin-desktop": "40px",
        "container-max": "1280px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "stack-md": "16px"
      },
      fontFamily: {
        "body-lg": ["Manrope", "sans-serif"],
        "title-md": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "body-sm": ["Manrope", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "title-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "800" }],
        "data-mono": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "800" }],
        "display-lg": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.03em", "fontWeight": "800" }]
      }
    }
  },
  plugins: [],
}
